name: PR checks

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: mbedos/mbed-os-env:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: app-f412g-starter
      - name: Compile
        working-directory: app-f412g-starter
        run: |
          mbed deploy
          mbed compile -t GCC_ARM -m F412G_DISCO
